/**
 * 怪物属性表（随层解锁）
 * 行动条满 100；速度 = 每 0.1 秒增加的点数
 */

export const GAUGE_MAX = 100;
export const DEFAULT_MONSTER_SPEED = 15;

/** 怪物攻击整体倍率（相对表内基础） */
export const MONSTER_ATK_MULT = 0.7;

export const MONSTER_STATS = {
  slime: {
    id: "slime",
    name: "史莱姆",
    color: "#ff6b6b",
    shape: "square",
    hp: 55,
    atk: 29,
    def: 3,
    spd: DEFAULT_MONSTER_SPEED,
    exp: 1,
    gold: 8,
    unlockFloor: 1,
    aiRole: "tank",
  },
  bat: {
    id: "bat",
    name: "吸血蝠",
    color: "#8b6cff",
    shape: "square",
    hp: 40,
    atk: 34,
    def: 2,
    spd: DEFAULT_MONSTER_SPEED + 6,
    exp: 2,
    gold: 11,
    unlockFloor: 2,
    aiRole: "dps",
  },
  goblin: {
    id: "goblin",
    name: "小哥布林",
    color: "#5dbf6a",
    shape: "square",
    hp: 62,
    atk: 36,
    def: 4,
    spd: DEFAULT_MONSTER_SPEED + 2,
    exp: 2,
    gold: 15,
    unlockFloor: 3,
    aiRole: "dps",
  },
  mushroom: {
    id: "mushroom",
    name: "毒菇精",
    color: "#e8a0ff",
    shape: "square",
    hp: 72,
    atk: 32,
    def: 5,
    spd: DEFAULT_MONSTER_SPEED - 2,
    exp: 3,
    gold: 20,
    unlockFloor: 5,
    aiRole: "support",
  },
  golem: {
    id: "golem",
    name: "石傀儡",
    color: "#a09080",
    shape: "square",
    hp: 118,
    atk: 45,
    def: 11,
    spd: DEFAULT_MONSTER_SPEED - 5,
    exp: 4,
    gold: 28,
    unlockFloor: 7,
    aiRole: "tank",
  },
  wisp: {
    id: "wisp",
    name: "幽光萤",
    color: "#7ec8ff",
    shape: "square",
    hp: 50,
    atk: 40,
    def: 3,
    spd: DEFAULT_MONSTER_SPEED + 4,
    exp: 4,
    gold: 24,
    unlockFloor: 8,
    aiRole: "support",
  },
  skeleton: {
    id: "skeleton",
    name: "枯骨兵",
    color: "#d8d0c0",
    shape: "square",
    hp: 88,
    atk: 48,
    def: 6,
    spd: DEFAULT_MONSTER_SPEED + 1,
    exp: 5,
    gold: 32,
    unlockFloor: 12,
    aiRole: "tank",
  },
  spider: {
    id: "spider",
    name: "毒囊蛛",
    color: "#6bcf8a",
    shape: "square",
    hp: 74,
    atk: 54,
    def: 4,
    spd: DEFAULT_MONSTER_SPEED + 5,
    exp: 6,
    gold: 38,
    unlockFloor: 15,
    aiRole: "dps",
  },
  wolf: {
    id: "wolf",
    name: "暗影狼",
    color: "#7a8aaa",
    shape: "square",
    hp: 98,
    atk: 60,
    def: 5,
    spd: DEFAULT_MONSTER_SPEED + 7,
    exp: 6,
    gold: 44,
    unlockFloor: 18,
    aiRole: "dps",
  },
  harpy: {
    id: "harpy",
    name: "血羽妖",
    color: "#ff8f6b",
    shape: "square",
    hp: 82,
    atk: 66,
    def: 4,
    spd: DEFAULT_MONSTER_SPEED + 8,
    exp: 7,
    gold: 50,
    unlockFloor: 22,
    aiRole: "dps",
  },
  knight: {
    id: "knight",
    name: "堕落骑士",
    color: "#9aa4b8",
    shape: "square",
    hp: 148,
    atk: 68,
    def: 15,
    spd: DEFAULT_MONSTER_SPEED - 3,
    exp: 9,
    gold: 60,
    unlockFloor: 25,
    aiRole: "tank",
  },
  mage: {
    id: "mage",
    name: "咒术师",
    color: "#c77dff",
    shape: "square",
    hp: 78,
    atk: 76,
    def: 3,
    spd: DEFAULT_MONSTER_SPEED + 3,
    exp: 9,
    gold: 66,
    unlockFloor: 28,
    aiRole: "support",
  },
  ogre: {
    id: "ogre",
    name: "食人魔",
    color: "#c4a06a",
    shape: "square",
    hp: 190,
    atk: 82,
    def: 13,
    spd: DEFAULT_MONSTER_SPEED - 4,
    exp: 11,
    gold: 78,
    unlockFloor: 32,
    aiRole: "tank",
  },
  shadow: {
    id: "shadow",
    name: "影魔",
    color: "#4a3a6a",
    shape: "square",
    hp: 95,
    atk: 88,
    def: 5,
    spd: DEFAULT_MONSTER_SPEED + 9,
    exp: 12,
    gold: 86,
    unlockFloor: 35,
    aiRole: "dps",
  },
  frost: {
    id: "frost",
    name: "霜噬灵",
    color: "#a8e4ff",
    shape: "square",
    hp: 118,
    atk: 80,
    def: 9,
    spd: DEFAULT_MONSTER_SPEED + 1,
    exp: 13,
    gold: 94,
    unlockFloor: 40,
    aiRole: "support",
  },
  demon: {
    id: "demon",
    name: "深渊魔",
    color: "#e05050",
    shape: "square",
    hp: 170,
    atk: 96,
    def: 11,
    spd: DEFAULT_MONSTER_SPEED + 3,
    exp: 15,
    gold: 110,
    unlockFloor: 45,
    aiRole: "dps",
  },
  dragon: {
    id: "dragon",
    name: "幼龙",
    color: "#e8b020",
    shape: "square",
    hp: 230,
    atk: 102,
    def: 16,
    spd: DEFAULT_MONSTER_SPEED - 1,
    exp: 18,
    gold: 130,
    unlockFloor: 48,
    aiRole: "dps",
  },
  boss: {
    id: "boss",
    name: "关口守护者",
    color: "#b44dff",
    shape: "square",
    hp: 200,
    atk: 30,
    def: 10,
    spd: DEFAULT_MONSTER_SPEED - 2,
    exp: 12,
    gold: 80,
    unlockFloor: 1,
    aiRole: "dps",
  },

  // —— 十种层固定主题 Boss（循环 1～10 / 11～20 …）——
  boss_sun: {
    id: "boss_sun",
    name: "日冕卫士",
    color: "#f0c040",
    shape: "square",
    hp: 210,
    atk: 30,
    def: 11,
    spd: DEFAULT_MONSTER_SPEED - 2,
    exp: 14,
    gold: 88,
    unlockFloor: 1,
    aiRole: "dps",
  },
  boss_sand: {
    id: "boss_sand",
    name: "沙角巨蟹",
    color: "#d4a574",
    shape: "square",
    hp: 230,
    atk: 28,
    def: 14,
    spd: DEFAULT_MONSTER_SPEED - 4,
    exp: 14,
    gold: 90,
    unlockFloor: 1,
    aiRole: "tank",
  },
  boss_tide: {
    id: "boss_tide",
    name: "潮冕祭司",
    color: "#4ec3f7",
    shape: "square",
    hp: 200,
    atk: 32,
    def: 10,
    spd: DEFAULT_MONSTER_SPEED - 1,
    exp: 15,
    gold: 96,
    unlockFloor: 1,
    aiRole: "dps",
  },
  boss_harbor: {
    id: "boss_harbor",
    name: "双湾港监",
    color: "#6a8aaa",
    shape: "square",
    hp: 220,
    atk: 34,
    def: 12,
    spd: DEFAULT_MONSTER_SPEED - 2,
    exp: 15,
    gold: 98,
    unlockFloor: 1,
    aiRole: "tank",
  },
  boss_mist: {
    id: "boss_mist",
    name: "雾林树妖",
    color: "#6bcf8a",
    shape: "square",
    hp: 240,
    atk: 31,
    def: 9,
    spd: DEFAULT_MONSTER_SPEED + 1,
    exp: 16,
    gold: 105,
    unlockFloor: 1,
    aiRole: "support",
  },
  boss_reef: {
    id: "boss_reef",
    name: "环礁海巫",
    color: "#7ec8ff",
    shape: "square",
    hp: 250,
    atk: 30,
    def: 11,
    spd: DEFAULT_MONSTER_SPEED - 1,
    exp: 16,
    gold: 108,
    unlockFloor: 1,
    aiRole: "support",
  },
  boss_dual: {
    id: "boss_dual",
    name: "双殿石像",
    color: "#a09080",
    shape: "square",
    hp: 260,
    atk: 29,
    def: 16,
    spd: DEFAULT_MONSTER_SPEED - 5,
    exp: 17,
    gold: 112,
    unlockFloor: 1,
    aiRole: "tank",
  },
  boss_ruin: {
    id: "boss_ruin",
    name: "退台亡王",
    color: "#c4a06a",
    shape: "square",
    hp: 215,
    atk: 36,
    def: 10,
    spd: DEFAULT_MONSTER_SPEED - 2,
    exp: 17,
    gold: 115,
    unlockFloor: 1,
    aiRole: "dps",
  },
  boss_saw: {
    id: "boss_saw",
    name: "锯湾海怪",
    color: "#ff8f6b",
    shape: "square",
    hp: 205,
    atk: 35,
    def: 9,
    spd: DEFAULT_MONSTER_SPEED + 2,
    exp: 18,
    gold: 118,
    unlockFloor: 1,
    aiRole: "dps",
  },
  boss_claw: {
    id: "boss_claw",
    name: "终焉爪兽",
    color: "#e05070",
    shape: "square",
    hp: 280,
    atk: 38,
    def: 13,
    spd: DEFAULT_MONSTER_SPEED - 1,
    exp: 20,
    gold: 130,
    unlockFloor: 1,
    aiRole: "dps",
  },
  boss_fool: {
    id: "boss_fool",
    name: "愚人隐者",
    color: "#c9a227",
    shape: "square",
    hp: 260,
    atk: 34,
    def: 12,
    spd: DEFAULT_MONSTER_SPEED + 2,
    exp: 28,
    gold: 140,
    unlockFloor: 14,
    aiRole: "support",
  },
};

export function getMonsterStats(id) {
  const data = MONSTER_STATS[id];
  if (!data) throw new Error(`未知怪物属性: ${id}`);
  return data;
}

function isBossSheetId(id) {
  return id === "boss" || String(id || "").startsWith("boss_");
}

/** 该层可刷的小怪类型（不含 boss） */
export function trashTypesForFloor(floor) {
  const f = Math.max(1, floor || 1);
  return Object.values(MONSTER_STATS).filter(
    (m) => !isBossSheetId(m.id) && (m.unlockFloor || 1) <= f
  );
}
