/**
 * 怪物属性表（随层解锁）
 * 行动条满 100；速度 = 每 0.1 秒增加的点数
 */

export const GAUGE_MAX = 100;
export const DEFAULT_MONSTER_SPEED = 15;

export const MONSTER_STATS = {
  slime: {
    id: "slime",
    name: "史莱姆",
    color: "#ff6b6b",
    shape: "square",
    hp: 55,
    atk: 29,
    def: 3,
    spd: DEFAULT_MONSTER_SPEED,
    exp: 1,
    gold: 8,
    unlockFloor: 1,
  },
  bat: {
    id: "bat",
    name: "吸血蝠",
    color: "#8b6cff",
    shape: "square",
    hp: 40,
    atk: 34,
    def: 2,
    spd: DEFAULT_MONSTER_SPEED + 6,
    exp: 2,
    gold: 11,
    unlockFloor: 2,
  },
  goblin: {
    id: "goblin",
    name: "小哥布林",
    color: "#5dbf6a",
    shape: "square",
    hp: 62,
    atk: 36,
    def: 4,
    spd: DEFAULT_MONSTER_SPEED + 2,
    exp: 2,
    gold: 15,
    unlockFloor: 3,
  },
  mushroom: {
    id: "mushroom",
    name: "毒菇精",
    color: "#e8a0ff",
    shape: "square",
    hp: 72,
    atk: 32,
    def: 5,
    spd: DEFAULT_MONSTER_SPEED - 2,
    exp: 3,
    gold: 20,
    unlockFloor: 5,
  },
  golem: {
    id: "golem",
    name: "石傀儡",
    color: "#a09080",
    shape: "square",
    hp: 118,
    atk: 45,
    def: 11,
    spd: DEFAULT_MONSTER_SPEED - 5,
    exp: 4,
    gold: 28,
    unlockFloor: 7,
  },
  wisp: {
    id: "wisp",
    name: "幽光萤",
    color: "#7ec8ff",
    shape: "square",
    hp: 50,
    atk: 40,
    def: 3,
    spd: DEFAULT_MONSTER_SPEED + 4,
    exp: 4,
    gold: 24,
    unlockFloor: 8,
  },
  skeleton: {
    id: "skeleton",
    name: "枯骨兵",
    color: "#d8d0c0",
    shape: "square",
    hp: 88,
    atk: 48,
    def: 6,
    spd: DEFAULT_MONSTER_SPEED + 1,
    exp: 5,
    gold: 32,
    unlockFloor: 12,
  },
  spider: {
    id: "spider",
    name: "毒囊蛛",
    color: "#6bcf8a",
    shape: "square",
    hp: 74,
    atk: 54,
    def: 4,
    spd: DEFAULT_MONSTER_SPEED + 5,
    exp: 6,
    gold: 38,
    unlockFloor: 15,
  },
  wolf: {
    id: "wolf",
    name: "暗影狼",
    color: "#7a8aaa",
    shape: "square",
    hp: 98,
    atk: 60,
    def: 5,
    spd: DEFAULT_MONSTER_SPEED + 7,
    exp: 6,
    gold: 44,
    unlockFloor: 18,
  },
  harpy: {
    id: "harpy",
    name: "血羽妖",
    color: "#ff8f6b",
    shape: "square",
    hp: 82,
    atk: 66,
    def: 4,
    spd: DEFAULT_MONSTER_SPEED + 8,
    exp: 7,
    gold: 50,
    unlockFloor: 22,
  },
  knight: {
    id: "knight",
    name: "堕落骑士",
    color: "#9aa4b8",
    shape: "square",
    hp: 148,
    atk: 68,
    def: 15,
    spd: DEFAULT_MONSTER_SPEED - 3,
    exp: 9,
    gold: 60,
    unlockFloor: 25,
  },
  mage: {
    id: "mage",
    name: "咒术师",
    color: "#c77dff",
    shape: "square",
    hp: 78,
    atk: 76,
    def: 3,
    spd: DEFAULT_MONSTER_SPEED + 3,
    exp: 9,
    gold: 66,
    unlockFloor: 28,
  },
  ogre: {
    id: "ogre",
    name: "食人魔",
    color: "#c4a06a",
    shape: "square",
    hp: 190,
    atk: 82,
    def: 13,
    spd: DEFAULT_MONSTER_SPEED - 4,
    exp: 11,
    gold: 78,
    unlockFloor: 32,
  },
  shadow: {
    id: "shadow",
    name: "影魔",
    color: "#4a3a6a",
    shape: "square",
    hp: 95,
    atk: 88,
    def: 5,
    spd: DEFAULT_MONSTER_SPEED + 9,
    exp: 12,
    gold: 86,
    unlockFloor: 35,
  },
  frost: {
    id: "frost",
    name: "霜噬灵",
    color: "#a8e4ff",
    shape: "square",
    hp: 118,
    atk: 80,
    def: 9,
    spd: DEFAULT_MONSTER_SPEED + 1,
    exp: 13,
    gold: 94,
    unlockFloor: 40,
  },
  demon: {
    id: "demon",
    name: "深渊魔",
    color: "#e05050",
    shape: "square",
    hp: 170,
    atk: 96,
    def: 11,
    spd: DEFAULT_MONSTER_SPEED + 3,
    exp: 15,
    gold: 110,
    unlockFloor: 45,
  },
  dragon: {
    id: "dragon",
    name: "幼龙",
    color: "#e8b020",
    shape: "square",
    hp: 230,
    atk: 102,
    def: 16,
    spd: DEFAULT_MONSTER_SPEED - 1,
    exp: 18,
    gold: 130,
    unlockFloor: 48,
  },
  boss: {
    id: "boss",
    name: "关口守护者",
    color: "#b44dff",
    shape: "square",
    hp: 200,
    atk: 30,
    def: 10,
    spd: DEFAULT_MONSTER_SPEED - 2,
    exp: 12,
    gold: 80,
    unlockFloor: 1,
  },
};

export function getMonsterStats(id) {
  const data = MONSTER_STATS[id];
  if (!data) throw new Error(`未知怪物属性: ${id}`);
  return data;
}

/** 该层可刷的小怪类型（不含 boss） */
export function trashTypesForFloor(floor) {
  const f = Math.max(1, floor || 1);
  return Object.values(MONSTER_STATS).filter(
    (m) => m.id !== "boss" && (m.unlockFloor || 1) <= f
  );
}
