/**
 * 怪物属性表（随层解锁）
 * 设计源：力/智/敏；战斗属性由怪物专用换算表得出（与英雄系数分开）。
 * 力：生命、防御、普攻；智：生命、魔向攻击、技能强度；敏：速度、少量普攻。
 * Boss 可带 hpBonus（额外生命），用于高血低攻体型。
 * 行动条满 100；速度 = 每 0.1 秒增加的点数
 */

import { readPrimary } from "../characters/primary.js?v=181";

export const GAUGE_MAX = 100;
export const DEFAULT_MONSTER_SPEED = 15;

/** 怪物攻击整体倍率（相对换算后的攻击） */
export const MONSTER_ATK_MULT = 0.63;

/** 怪物力智敏 → 战斗属性（保住旧表攻防曲线） */
export const MONSTER_PRIMARY_CONVERT = {
  hpBase: 18,
  strHp: 1.55,
  intHp: 0.55,
  strAtk: 0.55,
  intAtk: 0.7,
  agiAtk: 0.45,
  strDef: 0.14,
  intDef: 0.04,
  spdBase: 8,
  agiSpd: 0.5,
  intSkill: 0.85,
  strSkill: 0.2,
};

export function convertMonsterPrimary(str, int, agi, hpBonus = 0) {
  const c = MONSTER_PRIMARY_CONVERT;
  const S = Math.max(0, Number(str) || 0);
  const I = Math.max(0, Number(int) || 0);
  const A = Math.max(0, Number(agi) || 0);
  const bonus = Math.max(0, Math.floor(Number(hpBonus) || 0));
  const hp = Math.max(1, Math.floor(c.hpBase + S * c.strHp + I * c.intHp + bonus));
  return {
    hp,
    maxHp: hp,
    atk: Math.max(1, Math.floor(S * c.strAtk + I * c.intAtk + A * c.agiAtk)),
    def: Math.max(0, Math.floor(S * c.strDef + I * c.intDef)),
    spd: Math.max(1, Math.floor(c.spdBase + A * c.agiSpd)),
    skillAtk: Math.max(1, Math.floor(I * c.intSkill + S * c.strSkill)),
  };
}

/** 力/智/敏 → 战斗属性（未乘层 scale / MONSTER_ATK_MULT） */
export function monsterCombatFromPrimary(str, int, agi, hpBonus = 0) {
  return convertMonsterPrimary(str, int, agi, hpBonus);
}

export const MONSTER_STATS = {
  slime: {
    id: "slime",
    name: "史莱姆",
    color: "#ff6b6b",
    shape: "square",
    str: 19,
    int: 17,
    agi: 15,
    exp: 1,
    gold: 8,
    unlockFloor: 1,
    aiRole: "tank",
  },
  bat: {
    id: "bat",
    name: "吸血蝠",
    color: "#8b6cff",
    shape: "square",
    str: 7,
    int: 26,
    agi: 27,
    exp: 2,
    gold: 11,
    unlockFloor: 2,
    aiRole: "dps",
  },
  goblin: {
    id: "goblin",
    name: "小哥布林",
    color: "#5dbf6a",
    shape: "square",
    str: 22,
    int: 23,
    agi: 18,
    exp: 2,
    gold: 15,
    unlockFloor: 3,
    aiRole: "dps",
  },
  mushroom: {
    id: "mushroom",
    name: "毒菇精",
    color: "#e8a0ff",
    shape: "square",
    str: 32,
    int: 15,
    agi: 10,
    exp: 3,
    gold: 20,
    unlockFloor: 5,
    aiRole: "support",
  },
  golem: {
    id: "golem",
    name: "石傀儡",
    color: "#a09080",
    shape: "square",
    str: 60,
    int: 15,
    agi: 4,
    exp: 4,
    gold: 28,
    unlockFloor: 7,
    aiRole: "tank",
  },
  wisp: {
    id: "wisp",
    name: "幽光萤",
    color: "#7ec8ff",
    shape: "square",
    str: 8,
    int: 37,
    agi: 22,
    exp: 4,
    gold: 24,
    unlockFloor: 8,
    aiRole: "support",
  },
  skeleton: {
    id: "skeleton",
    name: "枯骨兵",
    color: "#d8d0c0",
    shape: "square",
    str: 34,
    int: 32,
    agi: 16,
    exp: 5,
    gold: 32,
    unlockFloor: 12,
    aiRole: "tank",
  },
  spider: {
    id: "spider",
    name: "毒囊蛛",
    color: "#6bcf8a",
    shape: "square",
    str: 20,
    int: 46,
    agi: 24,
    exp: 6,
    gold: 38,
    unlockFloor: 15,
    aiRole: "dps",
  },
  wolf: {
    id: "wolf",
    name: "暗影狼",
    color: "#7a8aaa",
    shape: "square",
    str: 38,
    int: 39,
    agi: 28,
    exp: 6,
    gold: 44,
    unlockFloor: 18,
    aiRole: "dps",
  },
  harpy: {
    id: "harpy",
    name: "血羽妖",
    color: "#ff8f6b",
    shape: "square",
    str: 17,
    int: 63,
    agi: 30,
    exp: 7,
    gold: 50,
    unlockFloor: 22,
    aiRole: "dps",
  },
  knight: {
    id: "knight",
    name: "堕落骑士",
    color: "#9aa4b8",
    shape: "square",
    str: 77,
    int: 31,
    agi: 9,
    exp: 9,
    gold: 60,
    unlockFloor: 25,
    aiRole: "tank",
  },
  mage: {
    id: "mage",
    name: "咒术师",
    color: "#c77dff",
    shape: "square",
    str: 7,
    int: 91,
    agi: 20,
    exp: 9,
    gold: 66,
    unlockFloor: 28,
    aiRole: "support",
  },
  ogre: {
    id: "ogre",
    name: "食人魔",
    color: "#c4a06a",
    shape: "square",
    str: 96,
    int: 38,
    agi: 6,
    exp: 11,
    gold: 78,
    unlockFloor: 32,
    aiRole: "tank",
  },
  shadow: {
    id: "shadow",
    name: "影魔",
    color: "#4a3a6a",
    shape: "square",
    str: 16,
    int: 93,
    agi: 32,
    exp: 12,
    gold: 86,
    unlockFloor: 35,
    aiRole: "dps",
  },
  frost: {
    id: "frost",
    name: "霜噬灵",
    color: "#a8e4ff",
    shape: "square",
    str: 38,
    int: 75,
    agi: 16,
    exp: 13,
    gold: 94,
    unlockFloor: 40,
    aiRole: "support",
  },
  demon: {
    id: "demon",
    name: "深渊魔",
    color: "#e05050",
    shape: "square",
    str: 73,
    int: 67,
    agi: 20,
    exp: 15,
    gold: 110,
    unlockFloor: 45,
    aiRole: "dps",
  },
  dragon: {
    id: "dragon",
    name: "幼龙",
    color: "#e8b020",
    shape: "square",
    str: 122,
    int: 43,
    agi: 12,
    exp: 18,
    gold: 130,
    unlockFloor: 48,
    aiRole: "dps",
  },
  boss: {
    id: "boss",
    name: "关口守护者",
    color: "#b44dff",
    shape: "square",
    str: 51,
    int: 0,
    agi: 8,
    hpBonus: 103,
    exp: 12,
    gold: 80,
    unlockFloor: 1,
    aiRole: "dps",
  },
  boss_sun: {
    id: "boss_sun",
    name: "日冕卫士",
    color: "#f0c040",
    shape: "square",
    str: 51,
    int: 0,
    agi: 8,
    hpBonus: 113,
    exp: 14,
    gold: 88,
    unlockFloor: 1,
    aiRole: "dps",
  },
  boss_sand: {
    id: "boss_sand",
    name: "沙角巨蟹",
    color: "#d4a574",
    shape: "square",
    str: 51,
    int: 0,
    agi: 4,
    hpBonus: 133,
    exp: 14,
    gold: 90,
    unlockFloor: 1,
    aiRole: "tank",
  },
  boss_tide: {
    id: "boss_tide",
    name: "潮冕祭司",
    color: "#4ec3f7",
    shape: "square",
    str: 50,
    int: 0,
    agi: 12,
    hpBonus: 105,
    exp: 15,
    gold: 96,
    unlockFloor: 1,
    aiRole: "dps",
  },
  boss_harbor: {
    id: "boss_harbor",
    name: "双湾港监",
    color: "#6a8aaa",
    shape: "square",
    str: 58,
    int: 0,
    agi: 8,
    hpBonus: 113,
    exp: 15,
    gold: 98,
    unlockFloor: 1,
    aiRole: "tank",
  },
  boss_mist: {
    id: "boss_mist",
    name: "雾林树妖",
    color: "#6bcf8a",
    shape: "square",
    str: 50,
    int: 0,
    agi: 12,
    hpBonus: 145,
    exp: 16,
    gold: 105,
    unlockFloor: 1,
    aiRole: "support",
  },
  boss_reef: {
    id: "boss_reef",
    name: "环礁海巫",
    color: "#7ec8ff",
    shape: "square",
    str: 50,
    int: 1,
    agi: 8,
    hpBonus: 154,
    exp: 16,
    gold: 108,
    unlockFloor: 1,
    aiRole: "support",
  },
  boss_dual: {
    id: "boss_dual",
    name: "双殿石像",
    color: "#a09080",
    shape: "square",
    str: 58,
    int: 0,
    agi: 0,
    hpBonus: 153,
    exp: 17,
    gold: 112,
    unlockFloor: 1,
    aiRole: "tank",
  },
  boss_ruin: {
    id: "boss_ruin",
    name: "退台亡王",
    color: "#c4a06a",
    shape: "square",
    str: 59,
    int: 0,
    agi: 10,
    hpBonus: 106,
    exp: 17,
    gold: 115,
    unlockFloor: 1,
    aiRole: "dps",
  },
  boss_saw: {
    id: "boss_saw",
    name: "锯湾海怪",
    color: "#ff8f6b",
    shape: "square",
    str: 50,
    int: 0,
    agi: 18,
    hpBonus: 110,
    exp: 18,
    gold: 118,
    unlockFloor: 1,
    aiRole: "dps",
  },
  boss_claw: {
    id: "boss_claw",
    name: "终焉爪兽",
    color: "#e05070",
    shape: "square",
    str: 66,
    int: 0,
    agi: 8,
    hpBonus: 160,
    exp: 20,
    gold: 130,
    unlockFloor: 1,
    aiRole: "dps",
  },
  boss_fool: {
    id: "boss_fool",
    name: "愚人隐者",
    color: "#c9a227",
    shape: "square",
    str: 50,
    int: 0,
    agi: 16,
    hpBonus: 165,
    exp: 28,
    gold: 140,
    unlockFloor: 14,
    aiRole: "support",
  },
};

export function getMonsterStats(id) {
  const data = MONSTER_STATS[id];
  if (!data) throw new Error(`未知怪物属性: ${id}`);
  const primary = readPrimary(data);
  const combat = monsterCombatFromPrimary(
    primary.str,
    primary.int,
    primary.agi,
    data.hpBonus || 0
  );
  return {
    ...data,
    ...primary,
    ...combat,
  };
}

function isBossSheetId(id) {
  return id === "boss" || String(id || "").startsWith("boss_");
}

/** 该层可刷的小怪类型（不含 boss） */
export function trashTypesForFloor(floor) {
  const f = Math.max(1, floor || 1);
  return Object.values(MONSTER_STATS).filter(
    (m) => !isBossSheetId(m.id) && (m.unlockFloor || 1) <= f
  );
}
